[2025-06-17T01:04:59.456+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T01:04:59.478+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2025-06-17T01:04:59.497+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T01:04:59.505+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2025-06-17T01:04:59.538+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-17T01:04:59.624+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_customers manual__2025-06-17T01:04:35.784223+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T01:04:59.634+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_customers manual__2025-06-17T01:04:35.784223+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-06-17T01:04:59.635+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_customers manual__2025-06-17T01:04:35.784223+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T01:04:59.635+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_customers manual__2025-06-17T01:04:35.784223+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-06-17T01:04:59.636+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_customers manual__2025-06-17T01:04:35.784223+00:00 [queued]>
[2025-06-17T01:04:59.636+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_customers manual__2025-06-17T01:04:35.784223+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T01:04:59.648+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_customers manual__2025-06-17T01:04:35.784223+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-06-17T01:04:59.648+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_customers manual__2025-06-17T01:04:35.784223+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-06-17T01:04:59.649+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_customers manual__2025-06-17T01:04:35.784223+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T01:04:59.649+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_customers manual__2025-06-17T01:04:35.784223+00:00 [queued]>
[2025-06-17T01:04:59.650+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-17T01:04:59.672+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_customers> on 2025-06-17 01:04:35.784223+00:00
[2025-06-17T01:04:59.683+0000] {standard_task_runner.py:63} INFO - Started process 325 to run task
[2025-06-17T01:04:59.689+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'globalsuperstore', 'transform.transform_dim_customers', 'manual__2025-06-17T01:04:35.784223+00:00', '--job-id', '297', '--raw', '--subdir', 'DAGS_FOLDER/global_superstore_dw_etl.py', '--cfg-path', '/tmp/tmp9m4r27u9']
[2025-06-17T01:04:59.691+0000] {standard_task_runner.py:91} INFO - Job 297: Subtask transform.transform_dim_customers
[2025-06-17T01:04:59.696+0000] {cli_action_loggers.py:70} DEBUG - Calling callbacks: [<function default_action_log at 0x7f7042299750>]
[2025-06-17T01:04:59.769+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T01:04:59.777+0000] {task_command.py:426} INFO - Running <TaskInstance: globalsuperstore.transform.transform_dim_customers manual__2025-06-17T01:04:35.784223+00:00 [running]> on host 9b7c60adfed6
[2025-06-17T01:04:59.778+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 325)
[2025-06-17T01:04:59.779+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 325)
[2025-06-17T01:04:59.779+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-06-17T01:04:59.824+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T01:04:59.827+0000] {taskinstance.py:1845} DEBUG - Clearing XCom data
[2025-06-17T01:04:59.846+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-06-17T01:04:59.879+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-06-17T01:04:59.898+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='globalsuperstore' AIRFLOW_CTX_TASK_ID='transform.transform_dim_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-06-17T01:04:35.784223+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-17T01:04:35.784223+00:00'
[2025-06-17T01:04:59.899+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2025-06-17T01:04:59.899+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2025-06-17T01:04:59.900+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-17T01:04:59.928+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-17T01:04:59.941+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-17T01:04:59.980+0000] {logging_mixin.py:188} INFO - ✔ Đã xóa dữ liệu trong warehouse.dim_customer
[2025-06-17T01:05:00.004+0000] {logging_mixin.py:188} INFO - ✔ Đã xóa dữ liệu trong warehouse.dim_product
[2025-06-17T01:05:00.034+0000] {logging_mixin.py:188} INFO - ✔ Đã xóa dữ liệu trong warehouse.dim_date
[2025-06-17T01:05:00.065+0000] {logging_mixin.py:188} INFO - ✔ Đã xóa dữ liệu trong warehouse.dim_shipmode
[2025-06-17T01:05:00.100+0000] {logging_mixin.py:188} INFO - ✔ Đã xóa dữ liệu trong warehouse.dim_location
[2025-06-17T01:05:00.129+0000] {logging_mixin.py:188} INFO - ✔ Đã xóa dữ liệu trong warehouse.fact_sales
[2025-06-17T01:05:00.151+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-17T01:05:00.167+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-17T01:05:00.725+0000] {logging_mixin.py:188} INFO - ✔ Đã lưu dữ liệu vào warehouse.dim_customer (1590 dòng)
[2025-06-17T01:05:00.726+0000] {logging_mixin.py:188} INFO - ✔ Đã transform và lưu dữ liệu vào warehouse.dim_customer
[2025-06-17T01:05:00.727+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-17T01:05:00.728+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-17T01:05:00.729+0000] {__init__.py:77} DEBUG - Lineage called with inlets: [], outlets: []
[2025-06-17T01:05:00.739+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2025-06-17T01:05:00.740+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=globalsuperstore, task_id=transform.transform_dim_customers, run_id=manual__2025-06-17T01:04:35.784223+00:00, execution_date=20250617T010435, start_date=20250617T010459, end_date=20250617T010500
[2025-06-17T01:05:00.740+0000] {taskinstance.py:562} DEBUG - Task Duration set to 1.103324
[2025-06-17T01:05:00.753+0000] {cli_action_loggers.py:88} DEBUG - Calling callbacks: []
[2025-06-17T01:05:00.790+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-17T01:05:00.815+0000] {dagrun.py:931} DEBUG - number of tis tasks for <DagRun globalsuperstore @ 2025-06-17 01:04:35.784223+00:00: manual__2025-06-17T01:04:35.784223+00:00, state:running, queued_at: 2025-06-17 01:04:35.795964+00:00. externally triggered: True>: 6 task(s)
[2025-06-17T01:05:00.817+0000] {dagrun.py:952} DEBUG - number of scheduleable tasks for <DagRun globalsuperstore @ 2025-06-17 01:04:35.784223+00:00: manual__2025-06-17T01:04:35.784223+00:00, state:running, queued_at: 2025-06-17 01:04:35.795964+00:00. externally triggered: True>: 1 task(s)
[2025-06-17T01:05:00.817+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-17T01:04:35.784223+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T01:05:00.819+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-17T01:04:35.784223+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T01:05:00.821+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-17T01:04:35.784223+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_states=_UpstreamTIStates(success=3, skipped=0, failed=0, upstream_failed=0, removed=0, done=3, success_setup=0, skipped_setup=0), upstream_task_ids={'transform.transform_dim_locations', 'transform.transform_dim_date', 'transform.transform_dim_shipmode', 'transform.transform_dim_customers', 'transform.transform_dim_products'}
[2025-06-17T01:05:00.821+0000] {taskinstance.py:2066} DEBUG - Dependencies not met for <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-17T01:04:35.784223+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_states=_UpstreamTIStates(success=3, skipped=0, failed=0, upstream_failed=0, removed=0, done=3, success_setup=0, skipped_setup=0), upstream_task_ids={'transform.transform_dim_locations', 'transform.transform_dim_date', 'transform.transform_dim_shipmode', 'transform.transform_dim_customers', 'transform.transform_dim_products'}
[2025-06-17T01:05:00.826+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-17T01:05:00.830+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
