[2025-06-14T10:00:24.045+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-14T10:00:24.079+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: GlobalSuperStore_dw_etl.transform.transform_dim_customers manual__2025-06-14T09:59:38.016498+00:00 [queued]>
[2025-06-14T10:00:24.092+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: GlobalSuperStore_dw_etl.transform.transform_dim_customers manual__2025-06-14T09:59:38.016498+00:00 [queued]>
[2025-06-14T10:00:24.093+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-14T10:00:24.107+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_customers> on 2025-06-14 09:59:38.016498+00:00
[2025-06-14T10:00:24.114+0000] {standard_task_runner.py:63} INFO - Started process 1443 to run task
[2025-06-14T10:00:24.118+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'GlobalSuperStore_dw_etl', 'transform.transform_dim_customers', 'manual__2025-06-14T09:59:38.016498+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/global_superstore_dw_etl.py', '--cfg-path', '/tmp/tmp5ft1ogp8']
[2025-06-14T10:00:24.120+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask transform.transform_dim_customers
[2025-06-14T10:00:24.159+0000] {task_command.py:426} INFO - Running <TaskInstance: GlobalSuperStore_dw_etl.transform.transform_dim_customers manual__2025-06-14T09:59:38.016498+00:00 [running]> on host f3cca4675eb8
[2025-06-14T10:00:24.234+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='GlobalSuperStore_dw_etl' AIRFLOW_CTX_TASK_ID='transform.transform_dim_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-06-14T09:59:38.016498+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-14T09:59:38.016498+00:00'
[2025-06-14T10:00:24.236+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-14T10:00:24.601+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-14T10:00:24.616+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-14T10:00:24.632+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-14T10:00:24.646+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-14T10:00:24.802+0000] {logging_mixin.py:188} INFO - ✔ Đã transform và lưu dữ liệu vào warehouse.dim_customer
[2025-06-14T10:00:24.802+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-14T10:00:24.803+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-14T10:00:24.810+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=GlobalSuperStore_dw_etl, task_id=transform.transform_dim_customers, run_id=manual__2025-06-14T09:59:38.016498+00:00, execution_date=20250614T095938, start_date=20250614T100024, end_date=20250614T100024
[2025-06-14T10:00:24.853+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-14T10:00:24.868+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-14T10:00:24.870+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
